---
title: "Shrub_map"
output: html_document
date: "2023-04-28"
---

```{r Load packages, include=FALSE, message=FALSE, warning=FALSE, echo=FALSE}
library(sf)
library(dplyr)
library(stringr)
library(leaflet)
library(leafgl)
```

```{r Load base layer, message=FALSE, warning=FALSE, echo=FALSE}
base_lyr <- st_read('./Spatial_Data/NA_lyr_clip.shp', quiet = T) %>% st_zm() %>% st_cast("POLYGON") %>% st_cast('LINESTRING')
```

```{r Read shrub layers, echo=FALSE}
fllst <- list.files(path = './Spatial_Data', pattern = '[.]gpkg', full.names = T)
shrub_fllst <- fllst[grepl('/SHRUB', fllst)]
shrub_lyrs <- lapply(shrub_fllst, st_read, quiet=T)
shrub_names <- shrub_fllst %>% str_split_i(pattern = '/', i = 3) %>% str_remove_all('[.]gpkg|SHRUB_')
names(shrub_lyrs) <- shrub_names
shrub_names <- names(shrub_lyrs) %>% str_replace_all('_', ' ')

shrub_pal <- c('#a6cee3','#1f78b4','#b2df8a','#33a02c','#fb9a99','#e31a1c','#fdbf6f','#ff7f00','#cab2d6','#6a3d9a','#ffff99','#b15928','#E600A9','#C500FF')

```

## Shrub species
```{r Map shrubs, echo=FALSE, message=FALSE, warning=FALSE}
m <- leaflet(width = 1100, height = 800, padding = 0, options = leafletOptions(minZoom = 5, maxZoom = 7)) %>% 
  addGlPolylines(base_lyr, color = 'black', weight = 0.5)

for (i in 1:length(shrub_lyrs)){
  m <- m %>% 
    addGlPoints(data = shrub_lyrs[[i]], fillColor = shrub_pal[i], group = shrub_names[i], fillOpacity = 1.0, radius = 5)
}

m <- m %>% 
  addLegend(colors = shrub_pal, labels = shrub_names, position = 'bottomright', opacity = 1.0) %>% 
  addLayersControl(overlayGroups = shrub_names) %>% 
  setMaxBounds(-109, 25, -58, 50) 

m
```

```{r echo=FALSE, results="asis"}
cat("
<style>
.leaflet-container {
    background: #FFF;
}
</style>
<style>
.info {
    font-style: italic;
}
</style>
")
```