---
title: "Supplemental Data"
output: html_document
date: "2023-10-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
library(DT)
```

```{r include=FALSE}
tb_1 <- read_xlsx('./Data/Supplemental Table 1_Systematic Review Papers.xlsx',
                sheet = 'Systematic Review Papers',
                range = 'A1:AN166') %>% 
  mutate(DOI = ifelse(is.na(DOI), NA, paste0("<a  href='", DOI, "'>", DOI,"</a>")))

tb_2 <- read_xlsx('./Data/Supplemental Table 1_Systematic Review Papers.xlsx',
                sheet = 'Herbicide',
                range = 'A1:E241')

tb_3 <- read_xlsx('./Data/Supplemental Table 1_Systematic Review Papers.xlsx',
                sheet = 'MetaData',
                range = 'A1:B41')

tb_4 <- read_xlsx('./Data/Supplemental Table 1_Systematic Review Papers.xlsx',
                sheet = 'Invasive Plant List',
                range = 'A2:E44')
```

## Systematic review papers
```{r echo=FALSE}
datatable(tb_1, 
          extensions = 'Scroller', 
          rownames = F,
          #width = 1000, 
          options = list(scrollY = 600,
                         scroller = T,
                         scrollX = 600,
                         pageLength = 5),
          escape = F)
```

## Herbicide
```{r echo=FALSE}
datatable(tb_2, 
          extensions = 'Scroller', 
          rownames = F,
          options = list(scrollY = 600,
               scroller = T,
               scrollX = 600,
               pageLength = 5))
```


## Metadata
```{r echo=FALSE}
datatable(tb_3, 
          extensions = 'Scroller', 
          rownames = F)

```

## Invasive plant list
```{r echo=FALSE}
datatable(tb_4, 
          extensions = 'Scroller', 
          rownames = F,
          #width = 1000, 
          options = list(scrollY = 600,
                         scroller = T,
                         scrollX = 600,
                         pageLength = 5))
```

Based on [USDA Plants Database](https://plants.usda.gov/home)

